
name: stack_test

preamble: |
    (declare-datatypes ((list 0))
      (((cons (head Int) (tail list)) (nil))))

state:
- name: 'x0'
  type: Int
- name: 'x1'
  type: Int
- name: 'x2'
  type: Int
- name: 'size'
  type: Int
- name: 'list_memory'
  type: list
- name: 'get_return'
  type: Int


states_equal:
  definition: |
    (ite (= size_1 0) (= list_memory_2 nil)
     (ite (= size_1 1) (and (= x0_1 (head list_memory_2)) (= (tail list_memory_2) nil))
      (ite (= size_1 2) (and (= x1_1 (head list_memory_2)) (= x0_1 (head (tail list_memory_2))) (= (tail (tail list_memory_2)) nil))
       (and (= x2_1 (head list_memory_2)) (= x1_1 (head (tail list_memory_2))) (= x0_1 (head (tail (tail list_memory_2)))) (= (tail (tail (tail list_memory_2))) nil))
      )
     )
    )

methods:
- name: pop
  args: []
  return:
  - name: val
    type: Int
  requires: |
    (> size 0)
  ensures: |
    (and (= size_new (- size 1))
         (= list_memory_new list_memory)
         (ite (= size 1) (and (= val x0) (= x0_new x0) (= x1_new x1) (= x2_new x2))
         (ite (= size 2) (and (= val x1) (= x0_new x0) (= x1_new x1) (= x2_new x2))
         (ite (= size 3) (and (= val x2) (= x0_new x0) (= x1_new x1) (= x2_new x2))
         true
         ))))
  terms: 
    Int: [0, 1, 'x0', 'x1', 'x2']

- name: pop_list_impl
  args: []
  return:
  - name: val
    type: Int
  requires: |
    (not (= list_memory nil))
  ensures: |
    (and (= val (head list_memory))
         (= list_memory_new (tail list_memory))
         (= x0_new x0) (= x1_new x1) (= x2_new x2) (= size_new size))
  terms: 
    Int: [0, 1, 'x0', 'x1', 'x2']

- name: get
  args:
  - name: index
    type: Int
  return:
  - name: val
    type: Int
  requires: |
    (and (< index size) (>= index 0))
  ensures: |
    (and (= size_new size)
         (= list_memory_new list_memory)
         (= x0_new x0) (= x1_new x1) (= x2_new x2)
         (ite (= index 0) (= get_return x0)
         (ite (= index 1) (= get_return x1)
         (ite (= index 2) (= get_return x2)
         true
         ))))
  terms: 
    Int: [0, 1, 'x0', 'x1', 'x2']

- name: get_impl
  args:
  - name: index
    type: Int
  return:
  - name: val
    type: Int
  requires: |
    (and (< index size) (>= index 0))
  ensures: |
    (and (= size_new size)
         (= list_memory_new list_memory)
         (= x0_new x0) (= x1_new x1) (= x2_new x2)
         (ite (= index 0) (= get_return (head list_memory))
         (ite (= index 1) (= get_return (head (tail list_memory)))
         (ite (= index 2) (= get_return (head (tail (tail list_memory))))
         true
         ))))
  terms: 
    Int: [0, 1, 'x0', 'x1', 'x2']


# pre-condition: (and (= size_l0 3) (not (= nil list_memory_r0)) (not (= nil (tail list_memory_r0))) (not (= nil (tail (tail list_memory_r0)))) (= x2_l0 (head list_memory_r0)) (= x1_l0 (head (tail list_memory_r0))) (= x0_l0 (head (tail (tail list_memory_r0)))) (= (tail (tail (tail list_memory_r0))) nil))
# ./servois2 verify ../yamls/stack.yml pop:pop_list_impl "(and (= size_l0 3) (not (= nil list_memory_r0)) (not (= nil (tail list_memory_r0))) (not (= nil (tail (tail list_memory_r0)))) (= x2_l0 (head list_memory_r0)) (= x1_l0 (head (tail list_memory_r0))) (= x0_l0 (head (tail (tail list_memory_r0)))) (= (tail (tail (tail list_memory_r0))) nil))" -vv

predicates:
  - name: "="
    type: [Int, Int]

